on: pull_request
name: Lint checks
jobs:
  black:
      name: Lint check
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: "Black Code Formatter"
          uses: "./.github/actions/black"
          with:
            args: ". --check"
            
  flake8:
    name: flake8 check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Flake8 check"
        uses: TrueBrain/actions-flake8@master
        with:
          ignore: E501,W  
